create table folders(
    id integer primary key generated by default as identity,
    folder_name text
);

create table notes(
    id integer generated by default as identity,
    content text not null,
    date_published timestamp default now() not null,
    folder_id integer references folders(id) on delete cascade not null,
    note_name text not null
);